CREATE TABLE users (
	id BIGSERIAL PRIMARY KEY,
	name TEXT,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	is_admin BOOLEAN NOT NULL,
	created_at TIMESTAMP DEFAULT NOW(),
	updated_at TIMESTAMP DEFAULT NOW(),
	deleted_at TIMESTAMP
)